### ISSUE TITLE
Panic when debugging with codelldb

### ISSUE THREAD

**Issue by antonwnk** [skim-rs/skim#542]
Hey!
I'm quite new to Rust and I'm not even sure if debugging on a binary using the skim library is supported without further tweaking on my side.  But I'll go ahead and ask/report what's happening in this issue.

I've copied over the examples/sample.rs code into a new project with skim 0.10.4 added as a dependency and I'm trying to debug it so I can explore the library better, line by line.
I'm running the codelldb debugger from my nvim which has a default dap installation (with the simrat39/rust-rtools plugin as well). The debugger seems to be working fine as I can step through the code from the example and also jump into the crate code, up until I get a panic at `tuikit::term::Term::with_options(...).unwrap` @ `lib.rs:319`.

This is the RUST_BACKTRACE=full output:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IOError(Os { code: 6, kind: Uncategorized, mess
age: "No such device or address" })', /home/anton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/skim-0.10.4/src/
lib.rs:319:14
stack backtrace:
   0:     0x555555b3ab01 - std::backtrace_rs::backtrace::libunwind::trace::he648b5c8dd376705
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/b
acktrace/libunwind.rs:93:5
   1:     0x555555b3ab01 - std::backtrace_rs::backtrace::trace_unsynchronized::h5da3e203eef39e9f
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/../../backtrace/src/b
acktrace/mod.rs:66:5
   2:     0x555555b3ab01 - std::sys_common::backtrace::_print_fmt::h8d28d3f20588ae4c
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.
rs:65:5
   3:     0x555555b3ab01 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd9a5b0c9
c6b058c0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.
rs:44:22
   4:     0x555555b616af - core::fmt::rt::Argument::fmt::h0afc04119f252b53
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/rt.rs:138:9
   5:     0x555555b616af - core::fmt::write::h50b1b3e73851a6fe
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/fmt/mod.rs:1094:21
   6:     0x555555b374e7 - std::io::Write::write_fmt::h184eaf275e4484f0
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/io/mod.rs:1714:15
   7:     0x555555b3a915 - std::sys_common::backtrace::_print::hf58c3a5a25090e71
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.
rs:47:5
   8:     0x555555b3a915 - std::sys_common::backtrace::print::hb9cf0a7c7f077819
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.
rs:34:9
   9:     0x555555b3bff3 - std::panicking::default_hook::{{closure}}::h066adb2e3f3e2c07
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:269:22
  10:     0x555555b3bd84 - std::panicking::default_hook::h277fa2776900ff14
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:288:9
  11:     0x555555b3c579 - std::panicking::rust_panic_with_hook::hceaf38da6d9db792
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:705:13
  12:     0x555555b3c477 - std::panicking::begin_panic_handler::{{closure}}::h2bce3ed2516af7df
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:597:13
  13:     0x555555b3af66 - std::sys_common::backtrace::__rust_end_short_backtrace::h090f3faf8f98a395
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.
rs:151:18
  14:     0x555555b3c1c2 - rust_begin_unwind
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:593:5
  15:     0x5555555ea923 - core::panicking::panic_fmt::h4ec8274704d163a3
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/panicking.rs:67:14
  16:     0x5555555eae53 - core::result::unwrap_failed::h170bc2721a6c6ff2
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1651:5
  17:     0x5555556d7581 - core::result::Result<T,E>::unwrap::h7605810da1d9f704
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/result.rs:1076:23
  18:     0x5555556e46d0 - skim::Skim::run_with::h5e922e48727913aa
                               at /home/anton/.cargo/registry/src/index.crates.io-6f17d22bba15001f/skim-0.10.4/src/lib.
rs:310:13
  19:     0x5555555eb26c - using_skim::main::h52ebf9f7d409acbc
                               at /home/anton/funcode/using-skim/src/main.rs:7:26
  20:     0x5555555eb89b - core::ops::function::FnOnce::call_once::h7e43a280927c01f4
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:250:
5
  21:     0x5555555ebb4e - std::sys_common::backtrace::__rust_begin_short_backtrace::h52d9627b47e83745
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/sys_common/backtrace.
rs:135:18
  22:     0x5555555eb851 - std::rt::lang_start::{{closure}}::hb2c480bd2c46ede4
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:166:18
  23:     0x555555b3338b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h75ba42
44a1c7bb54
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/core/src/ops/function.rs:284:
13
  24:     0x555555b3338b - std::panicking::try::do_call::h0a2baa36dea975a1
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  25:     0x555555b3338b - std::panicking::try::h0e42aa233d4224d4
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  26:     0x555555b3338b - std::panic::catch_unwind::hefdfd8f482606434
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  27:     0x555555b3338b - std::rt::lang_start_internal::{{closure}}::h457959f0f91da23b
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.rs:148:48
  28:     0x555555b3338b - std::panicking::try::do_call::h112cfd1acb38183b
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:500:40
  29:     0x555555b3338b - std::panicking::try::ha64f15b20cec18ca
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panicking.rs:464:19
  30:     0x555555b3338b - std::panic::catch_unwind::hbacc2b68ee2c119e
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/panic.rs:142:14
  22:     0x5555555eb851 - std::rt::lang_start::{{closure}}::hb2c480bd2c46ede4
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.r
  32:     0x5555555eb82a - std::rt::lang_start::h501a3c64902ef8fa
                               at /rustc/5680fa18feaa87f3ff04063800aec256c3d4b4be/library/std/src/rt.r
s:165:17
  33:     0x5555555eb52e - main
  34:     0x7ffff7c49083 - __libc_start_main
  35:     0x5555555eb15e - _start
  36:                0x0 - <unknown>

[Process exited 0]
```

Thanks in advance!

**Comment by LoricAndre** [comment]
This is not applicable anymore as it references tuikit, I'll be closing the issue, feel free to reopen if you can replicate it in the latest version.
