### ISSUE TITLE
Tried skim on debian

### ISSUE THREAD

**Issue by roukmoute** [skim-rs/skim#573]
I've tried skim on debian:

```sh
$ git clone --depth 1 git@github.com:lotabout/skim.git ~/.skim
$ cd ~/.skim/bin
$ RUST_BACKTRACE=full ./sk
thread 'main' panicked at 'command not found: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/helper/item_reader.rs:208:70
stack backtrace:
   0:           0x5cb86e - std::backtrace_rs::backtrace::libunwind::trace::h59cc641d388c5230
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:           0x5cb86e - std::backtrace_rs::backtrace::trace_unsynchronized::h5262229e9454a0e7
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:           0x5cb86e - std::sys_common::backtrace::_print_fmt::hef57fee145d10e3b
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:67:5
   3:           0x5cb86e - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h66de9fdffc4ffa63
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:46:22
   4:           0x45503c - core::fmt::write::habe0652f164aef90
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/fmt/mod.rs:1078:17
   5:           0x5caff1 - std::io::Write::write_fmt::h21709dd3ff2890c8
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/io/mod.rs:1517:15
   6:           0x5ca995 - std::sys_common::backtrace::_print::hab1e457c742fc786
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:49:5
   7:           0x5ca995 - std::sys_common::backtrace::print::h78282484978614fe
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:36:9
   8:           0x5ca995 - std::panicking::default_hook::{{closure}}::h46e04668dd2faedf
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:208:50
   9:           0x5ca05b - std::panicking::default_hook::h6bbf8d199657ce80
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:225:9
  10:           0x5ca05b - std::panicking::rust_panic_with_hook::h792be13c6c9ed904
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:591:17
  11:           0x5e8b08 - std::panicking::begin_panic_handler::{{closure}}::h408e419c79cbd8c2
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:497:13
  12:           0x5e8a7c - std::sys_common::backtrace::__rust_end_short_backtrace::hdbac08429ddbd395
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/sys_common/backtrace.rs:141:18
  13:           0x5e8a2d - rust_begin_unwind
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
  14:           0x452850 - core::panicking::panic_fmt::h43c59f6b709f9787
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
  15:           0x455aa2 - core::option::expect_none_failed::h8b73fc553520f3a4
                               at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
  16:           0x54a790 - skim::helper::item_reader::SkimItemReader::read_and_collect_from_command::h8e93e1f29dc04bad
  17:           0x54b001 - <skim::helper::item_reader::SkimItemReader as skim::reader::CommandCollector>::invoke::hb99d32b365b749f2
  18:           0x580f67 - skim::reader::Reader::run::h3fd6fb42c5e5ea92
  19:           0x58c19d - skim::model::Model::start::h2651e36205cc1110
  20:           0x5bab81 - skim::Skim::run_with::h4d8024049d0ca5d1
  21:           0x523b71 - sk::real_main::hdd114f05ea436c88
  22:           0x50d059 - sk::main::h89f622a838d73ff0
  23:           0x52fe13 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6ac66a2325a0bdac
  24:           0x50cf0f - main

```

**Comment by LoricAndre** [comment]
Do you have `find` installed and available in your `PATH` ?

**Comment by LoricAndre** [comment]
Please reopen if this is still an issue
